language: go
go:
  - 1.2
  - 1.5
  - 1.6
  - 1.7
  - 1.8rc3
env:
  global:
    - PKG_CONFIG_PATH="$HOME/gopath/src/github.com/confluentinc/confluent-kafka-go/tmp-build/lib/pkgconfig"
    - PATH="$PATH:$GOPATH/bin"
  matrix:
    - LIBRDKAFKA_VERSION=master
os:
  - linux
  - osx
before_install:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then export BUILD_TAGS="" ; else export BUILD_TAGS="-tags static" ; fi
  - rm -rf tmp-build
  - bash mk/bootstrap-librdkafka.sh ${LIBRDKAFKA_VERSION} tmp-build
  - if [[ $TRAVIS_GO_VERSION == 1.[78]* ]]; then go get -u github.com/golang/lint/golint ; fi
install:
  - go get $BUILD_TAGS ./...
  - go install $BUILD_TAGS ./...
  - (cd examples/go-kafkacat && go install $BUILD_TAGS)

script:
  - if [[ $TRAVIS_GO_VERSION == 1.[78]* ]]; then golint -set_exit_status ./... ; fi
  - go test -v $BUILD_TAGS ./...
  - go-kafkacat --help
