language: go
go:
  - 1.2
  - 1.5
  - 1.6
  - 1.7
before_install:
  - bash mk/bootstrap-librdkafka.sh v0.9.2 tmp-build
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint
env:
  global:
    - PKG_CONFIG_PATH="$HOME/gopath/src/github.com/confluentinc/confluent-kafka-go/tmp-build/lib/pkgconfig"
    - PATH="$PATH:$GOPATH/bin"
install:
  - go get -tags static ./...
  - go install -tags static ./...
  - (cd examples/go-kafkacat && go install -tags static)

script:
  - go vet ./...
  - golint ./...
  - go test -v -tags static ./...
  - go-kafkacat --help
